import { badRequest } from "@/lib/server/errors";

export const MAX_RECEIPT_BYTES = 5 * 1024 * 1024;

const TYPES = {
  jpg: { mime: "image/jpeg", exts: ["jpg", "jpeg"] },
  png: { mime: "image/png", exts: ["png"] },
  webp: { mime: "image/webp", exts: ["webp"] },
  pdf: { mime: "application/pdf", exts: ["pdf"] },
} as const;

/** Detect the real file type from its first bytes (never trust the client-supplied MIME type). */
function sniff(buf: Buffer): keyof typeof TYPES | null {
  if (buf.length < 12) return null;
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "jpg";
  if (buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "png";
  if (buf.subarray(0, 4).toString("latin1") === "RIFF" && buf.subarray(8, 12).toString("latin1") === "WEBP") return "webp";
  if (buf.subarray(0, 5).toString("latin1") === "%PDF-") return "pdf";
  return null;
}

export interface ValidatedUpload { ext: string; mime: string; size: number; originalName: string }

/**
 * Size, extension, declared MIME and magic-byte checks. The stored name is generated by the server;
 * the original name is kept only as display text (sanitised).
 */
export function validateReceipt(file: { name: string; type: string; size: number }, buf: Buffer): ValidatedUpload {
  if (buf.length === 0) throw badRequest("فایل خالی است.", "upload_empty");
  if (buf.length > MAX_RECEIPT_BYTES) throw badRequest("حجم فایل نباید بیشتر از ۵ مگابایت باشد.", "upload_too_large");
  const kind = sniff(buf);
  if (!kind) throw badRequest("فقط تصویر (JPG، PNG، WebP) یا PDF مجاز است.", "upload_type");
  const ext = (file.name.split(".").pop() ?? "").toLowerCase();
  if (!(TYPES[kind].exts as readonly string[]).includes(ext)) throw badRequest("پسوند فایل با محتوای آن نمی‌خواند.", "upload_ext");
  if (file.type && file.type !== TYPES[kind].mime && !(kind === "jpg" && file.type === "image/jpg")) throw badRequest("نوع فایل نامعتبر است.", "upload_mime");
  const originalName = file.name.replace(/[^\p{L}\p{N}._ -]/gu, "").slice(0, 80) || "receipt";
  return { ext: TYPES[kind].exts[0], mime: TYPES[kind].mime, size: buf.length, originalName };
}
